### PR TITLE
V2.2.0 rc1

### PR DESCRIPTION
**Pull request by bayu41**
update to parsley.js v2.2.0 rc1

### CODE REVIEW

**Comment by sgrosse** [comment]
+1

**Comment by sgrosse** [comment]
With this branch I get an error during deployment:

```
DEBUG [28ecbef8] 	There was a ArgumentError while loading parsley-rails.gemspec: 
DEBUG [28ecbef8] 	Malformed version number string 2.2.0-rc1 from
DEBUG [28ecbef8] 	/var/www/staging.farawayhome.de/shared/bundle/ruby/2.0.0/bundler/gems/parsley-rails-5913e363f4bf/parsley-rails.gemspec:8:in
DEBUG [28ecbef8] 	`block in <main>'```

**Comment by bayu41** [comment]
I think it's because "-rc1" let me remove it

**Comment by daande** [comment]
Is there any update on this being merged into master?

**Comment by bayu41** [comment]
yes, I have change the version from 2.2.0-rc1 to 2.2.0.0.
Would you like to re-deploy?

**Comment by tilsammans** [comment]
@jiripospisil can this be merged and/or updated to the latest parsley?

**Comment by jiripospisil** [comment]
Thank you. Superseded by #21.

**Pull request closed without merging**
